DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/Dev_Org_Setting__c.object-meta.xml
<CustomObject>
    <label>Dev Org Setting</label>
    <nameField>
        <label>Dev Org Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dev Org Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/ck__c.field-meta.xml
<CustomField>
    <fullName>ck__c</fullName>
    <label>CKey</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/cs__c.field-meta.xml
<CustomField>
    <fullName>cs__c</fullName>
    <label>CSec</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/pw__c.field-meta.xml
<CustomField>
    <fullName>pw__c</fullName>
    <label>pw</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/st__c.field-meta.xml
<CustomField>
    <fullName>st__c</fullName>
    <label>st</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/classes/TestDevOrgLoginFactory.cls
@isTest
public class TestDevOrgLoginFactory {


	public static List<Dev_Org_Setting__c> createDevOrgSettings(Integer numActive, Integer numInactive ){

		List<Dev_Org_Setting__c> devOrgSettings = new List<Dev_Org_Setting__c>();

		

		for(Integer i = 0; i < numActive; i++){
		
			devOrgSettings.add(
				new Dev_Org_Setting__c(
					Name = 'DevOrgTest' + i,
					Active__c = true,
					cs__c = 'CSKEY' + i,
					pw__c = 'pw' + i,
					Username__c = 'testdev' + i + '@testdev.test',
					ck__c = 'ck' + i,
 					Endpoint__c = 'https://test.salesforce.com',
 				        st__c = 'st' + i
				)
			);
		}

		for(Integer j = 0; j < numInactive; j++){
		
			devOrgSettings.add(
				new Dev_Org_Setting__c(
					Name = 'DevOrgTestInActive' + j,
					Active__c = false,
					cs__c = 'CSKEY' + j,
					pw__c = 'pw' + j,
					Username__c = 'testdev' + j + '@testdev.test',
					ck__c = 'ck' + j,
 					Endpoint__c = 'https://test.salesforce.com',
 				        st__c = 'st' + j
				)
			);

		}	
		


		try{
			insert devOrgSettings;
		}catch(Exception ex){
			System.debug(LoggingLevel.ERROR, 'Error during test dev org setting creation: ' + ex.getMessage());
		}


		return devOrgSettings;

	}


}