DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/Dev_Org_Setting__c.object-meta.xml
<CustomObject>
    <label>Dev Org Setting</label>
    <nameField>
        <label>Dev Org Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dev Org Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/ck__c.field-meta.xml
<CustomField>
    <fullName>ck__c</fullName>
    <label>CKey</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/cs__c.field-meta.xml
<CustomField>
    <fullName>cs__c</fullName>
    <label>CSec</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/pw__c.field-meta.xml
<CustomField>
    <fullName>pw__c</fullName>
    <label>pw</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/st__c.field-meta.xml
<CustomField>
    <fullName>st__c</fullName>
    <label>st</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/classes/ScheduleDevOrgLogin.cls
global  with sharing class ScheduleDevOrgLogin implements Schedulable{

	global void execute(SchedulableContext SC){

		String devOrgQuery = 'SELECT Id, Active__c, cs__c, st__c, ck__c, pw__c, Username__c, Endpoint__c '
		 		   + ' FROM Dev_Org_Setting__c WHERE Active__c = TRUE';
		
		DevOrgLoginBatch dlb = new DevOrgLoginBatch(devOrgQuery, 'Username__c', 
		'pw__c', 'st__c', 'Endpoint__c', 'ck__c', 'cs__c'); 		   

		Database.executeBatch(dlb, 1);

	
	}

}