DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Login_Result__c/Dev_Org_Login_Result__c.object-meta.xml
<CustomObject>
    <label>Dev Org Login Result</label>
    <nameField>
        <label>Dev Org Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dev Org Login Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Login_Result__c/fields/Dev_Org_Setting__c.field-meta.xml
<CustomField>
    <fullName>Dev_Org_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dev Org Setting</label>
    <referenceTo>Dev_Org_Setting__c</referenceTo>
    <relationshipLabel>Dev Org Login Results</relationshipLabel>
    <relationshipName>Dev_Org_Login_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/Dev_Org_Setting__c.object-meta.xml
<CustomObject>
    <label>Dev Org Setting</label>
    <nameField>
        <label>Dev Org Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dev Org Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevEditionAutoLogin/force-app/main/default/classes/DevOrgLoginBatch.cls
global with sharing class DevOrgLoginBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{

	global final String query;
	global final String pwField;
	global final String uField;
	global final String stField;
	global final String keyField;
	global final String csField;
	global final String endPtField;


	global DevOrgLoginBatch(String q, String u, String p, String st, String e, String k, String cs){
		query = q;
		pwField = p;
		uField = u;
		stField = st;
		keyField = k;
		csField = cs;
		endPtField = e;
	}

	global Database.QueryLocator start(Database.BatchableContext BC){
		System.debug('query: ' + query);
		return Database.getQueryLocator(query); 
	} 

	global void execute(Database.BatchableContext BC, List<sObject> scope){
	

		List<Dev_Org_Login_Result__c> loginResLst = new List<Dev_Org_Login_Result__c>();

		for(sObject sObj : scope){
			String u = (String)sObj.get(uField);
			String p = (String)sObj.get(pwField);
			String st = (String)sObj.get(stField);
			String ep = (String)sObj.get(endPtField);
			String ck = (String)sObj.get(keyField);
			String cs = (String)sObj.get(csField);


			Dev_Org_Login_Result__c lr =  DevOrgLoginService.login(u, p+st, ep, ck, cs);
			lr.Dev_Org_Setting__c = (String) sObj.get('Id');
			loginResLst.add(lr);
		}


		try{
			insert loginResLst;
		}catch(DMLException ex){
			System.debug(LoggingLevel.ERROR, 'Error during dev org login result insertion: ' + ex.getMessage());
		}
		
	}

	global void finish(Database.BatchableContext BC){
	}

}