DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Login_Result__c/Dev_Org_Login_Result__c.object-meta.xml
<CustomObject>
    <label>Dev Org Login Result</label>
    <nameField>
        <label>Dev Org Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dev Org Login Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Login_Result__c/fields/Dev_Org_Setting__c.field-meta.xml
<CustomField>
    <fullName>Dev_Org_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dev Org Setting</label>
    <referenceTo>Dev_Org_Setting__c</referenceTo>
    <relationshipLabel>Dev Org Login Results</relationshipLabel>
    <relationshipName>Dev_Org_Login_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Login_Result__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Stores error message from the login attempt</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/Dev_Org_Setting__c.object-meta.xml
<CustomObject>
    <label>Dev Org Setting</label>
    <nameField>
        <label>Dev Org Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dev Org Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/ck__c.field-meta.xml
<CustomField>
    <fullName>ck__c</fullName>
    <label>CKey</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/cs__c.field-meta.xml
<CustomField>
    <fullName>cs__c</fullName>
    <label>CSec</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/pw__c.field-meta.xml
<CustomField>
    <fullName>pw__c</fullName>
    <label>pw</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/st__c.field-meta.xml
<CustomField>
    <fullName>st__c</fullName>
    <label>st</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/classes/TestDevOrgLogin.cls
/**
 * @author Terence Chiu
 * @date 2020-01-17
 * @description Test class to test DevOrgLoginService methods
 *
 */
@isTest
private class TestDevOrgLogin {

    @testSetup
    static void setupDevOrgSettings(){

	List<Dev_Org_Setting__c> testDOSettings = TestDevOrgLoginFactory.createDevOrgSettings(4, 1);
	Integer numOfActive = 0;
	Integer numOfInactive = 0;
	Integer numOfCreated = 0;
	for(Dev_Org_Setting__c testDOS : testDOSettings){
		Boolean act = testDOS.Active__c;
		numOfActive = act ? numOfActive + 1 : numOfActive;
		numOfInactive = !act ? numOfInactive + 1 : numOfInActive;
		numOfCreated = testDOS.Id != null ? numOfCreated + 1 : numOfCreated;
	}

	System.assertEquals(4, numOfActive, 'Four setting records should be active');
	System.assertEquals(1, numOfInactive, 'one setting record should be inactive');
	System.assertEquals(5, numOfCreated, 'Five setting records should be inserted successfully');


	/*for(Integer i = 0; i < 5; i++){

		Boolean active = i == 4 ? false : true;
		testDOSettings.add(

			new Dev_Org_Setting__c(

				Name = 'DevOrgTest' + i,
				Active__c = active,
				cs__c = 'CSKEY' + i,
				pw__c = 'pw' + i,
				Username__c = 'testdev' + i + '@testdev.test',
				ck__c = 'ck' + i,
				Endpoint__c = 'https://test.salesforce.com',
				st__c = 'st' + i
				
			)
		);


	}*/

	/*try{
		insert testDOSettings;
	}catch(Exception ex){
		System.debug(LoggingLevel.ERROR, 'Error during test dev org setting setup: ' + ex.getMessage());
	}*/
	



    }


    @isTest
    static void testLoginSuccess() {

	MockDevOrgLoginResponseGen mockGen = new MockDevOrgLoginResponseGen(true);
//	List<Dev_Org_Login_Result__c> loginRes = new List<Dev_Org_Login_Result__c>();
	Integer successCnt = 0;
	List<Dev_Org_Setting__c> devOrgSetting = [SELECT Id, Username__c, cs__c, pw__c, ck__c, Endpoint__c, st__c ,Active__c FROM Dev_Org_Setting__c WHERE Active__c = TRUE];



	Test.startTest();

	Test.setMock(HttpCalloutMock.class, mockGen);
	
	for(Dev_Org_Setting__c dos : devOrgSetting){
		Dev_Org_Login_Result__c loginRes = DevOrgLoginService.login(dos.Username__c, dos.pw__c + dos.st__c, dos.Endpoint__c, dos.ck__c, dos.cs__c);
		successCnt = loginRes.Success__c ? successCnt + 1 : successCnt;
	}

	Test.stopTest();

	system.assertEquals(devOrgSetting.size(), successCnt, 'All four active dev org settings should result in a successful login attempt');

    
    }

    @isTest
    static void testLoginFailure() {

	MockDevOrgLoginResponseGen mockGen = new MockDevOrgLoginResponseGen(false);
//	List<Dev_Org_Login_Result__c> loginRes = new List<Dev_Org_Login_Result__c>();
	Integer errCnt = 0;
	List<Dev_Org_Setting__c> devOrgSetting = [SELECT Id, Username__c, cs__c, pw__c, ck__c, Endpoint__c, st__c ,Active__c FROM Dev_Org_Setting__c WHERE Active__c = TRUE];



	Test.startTest();

	Test.setMock(HttpCalloutMock.class, mockGen);
	
	for(Dev_Org_Setting__c dos : devOrgSetting){
		Dev_Org_Login_Result__c loginRes = DevOrgLoginService.login(dos.Username__c, dos.pw__c + dos.st__c, dos.Endpoint__c, dos.ck__c, dos.cs__c);
		errCnt = !loginRes.Success__c ? errCnt + 1 : errCnt;
	}

	Test.stopTest();

	system.assertEquals(devOrgSetting.size(), errCnt, 'All four active dev org settings should result in a failed login attempt');

      

    }


    @isTest
    static void testLoginCalloutEx() {

	MockDevOrgLoginResponseGen mockGen = new MockDevOrgLoginResponseGen(true);
//	List<Dev_Org_Login_Result__c> loginRes = new List<Dev_Org_Login_Result__c>();
	Integer errCnt = 0;
	List<Dev_Org_Setting__c> devOrgSetting = [SELECT Id, Username__c, cs__c, pw__c, ck__c, Endpoint__c, st__c ,Active__c FROM Dev_Org_Setting__c WHERE Active__c = TRUE];

	//Test.startTest();

	Test.setMock(HttpCalloutMock.class, mockGen);
	
	for(Dev_Org_Setting__c dos : devOrgSetting){
		Dev_Org_Login_Result__c loginRes = DevOrgLoginService.login(dos.Username__c, dos.pw__c + dos.st__c, dos.Endpoint__c, dos.ck__c, dos.cs__c);
		String exMsg = loginRes.Error_Message__c != null ? loginRes.Error_Message__c : '';
		errCnt = !loginRes.Success__c && exMsg.contains('Error during dev org login:') ? errCnt + 1 : errCnt;
	}

	//Test.stopTest();

	system.assertEquals(devOrgSetting.size(), errCnt, 'All four active dev org settings should result in a callout exception');

      
    }
    
    
}