DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Login_Result__c/Dev_Org_Login_Result__c.object-meta.xml
<CustomObject>
    <label>Dev Org Login Result</label>
    <nameField>
        <label>Dev Org Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dev Org Login Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Login_Result__c/fields/Dev_Org_Setting__c.field-meta.xml
<CustomField>
    <fullName>Dev_Org_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dev Org Setting</label>
    <referenceTo>Dev_Org_Setting__c</referenceTo>
    <relationshipLabel>Dev Org Login Results</relationshipLabel>
    <relationshipName>Dev_Org_Login_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/Dev_Org_Setting__c.object-meta.xml
<CustomObject>
    <label>Dev Org Setting</label>
    <nameField>
        <label>Dev Org Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dev Org Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/ck__c.field-meta.xml
<CustomField>
    <fullName>ck__c</fullName>
    <label>CKey</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/cs__c.field-meta.xml
<CustomField>
    <fullName>cs__c</fullName>
    <label>CSec</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/pw__c.field-meta.xml
<CustomField>
    <fullName>pw__c</fullName>
    <label>pw</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/objects/Dev_Org_Setting__c/fields/st__c.field-meta.xml
<CustomField>
    <fullName>st__c</fullName>
    <label>st</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

DevEditionAutoLogin/force-app/main/default/classes/TestDevOrgLoginBatch.cls
@isTest
private class TestDevOrgLoginBatch {


	@testSetup
	static void setupDevOrgSettings(){
		List<Dev_Org_Setting__c> testDOSettings = 
			TestDevOrgLoginFactory.createDevOrgSettings(10, 4);
			
	}

	@isTest
	static void testBatchLogin(){

		MockDevOrgLoginResponseGen mockGen = new MockDevOrgLoginResponseGen(true);
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, mockGen);
		

		String devOrgQuery = 'SELECT Id, Active__c, cs__c, st__c, ck__c, pw__c, Username__c, Endpoint__c '
		                                   + ' FROM Dev_Org_Setting__c WHERE Active__c = TRUE';
		
		DevOrgLoginBatch dlb = new DevOrgLoginBatch(devOrgQuery, 'Username__c', 
		                'pw__c', 'st__c', 'Endpoint__c', 'ck__c', 'cs__c');                
		                
		Database.executeBatch(dlb);
		                                 


		Test.stopTest();

		List<Dev_Org_Login_Result__c> loginRes = [SELECT Id FROM Dev_Org_Login_Result__c WHERE Success__c = TRUE];

		System.assertEquals(10, loginRes.size(), 'Batch execution should have resulted in 10 Successful login results');


	}



}